# ls
alias ll="ls -lah"

# git
alias gadd="git add"
alias gbranch="git branch"
alias gcheck="git checkout"
alias gcherry="git cherry-pick"
alias gclone="git clone"
alias gcommit="git commit"
alias gcommita="git commit --amend"
alias gdiff="git diff"
alias gfetch="git fetch"
alias ginit="git init"
alias gshow="git show"
alias gstatus="git status"
alias gstash="git stash"
alias gstasha="git stash apply"
alias glog="git log --graph"
alias gmerge="git merge"
alias gpull="git pull"
alias gpush="git push"
alias gpushoh="git push origin head"
alias gpushohf="git push origin head -f"
alias gremote="git remote"
alias gremoteao="git remote add origin"
alias gremotero="git remote remove origin"
alias greset="git reset"
alias greseth="git reset --hard"
alias grebase="git rebase"
alias grebasea="git rebase --abort"
alias grebasec="git rebase --continue"
alias grevert="git revert"
